import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "@/lib/providers/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import { revalidatePath } from "next/cache";
import LoadingSpinner from "@/components/ui/loading-spinner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AviAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  revalidatePath("/");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Suspense
            fallback={
              <div className="flex justify-center items-center h-screen">
                <LoadingSpinner />
              </div>
            }
          >
            {children}
          </Suspense>
        </QueryProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
